### ISSUE TITLE
raise ValueError("Tensor %s is not an element of this graph." % obj)

### ISSUE THREAD

**Issue by vinnitu** [jaredwinick/img2vec-keras#5]
Hello.

I try to use Img2Vec with Flask server but I get error.

How to properly fix it?

Thanks

**Comment by jaredwinick** [comment]
What versions of TensorFlow and Keras are you using? I have never seen that issue but it looks related to what is discussed here https://github.com/keras-team/keras/issues/6462#issuecomment-385962748 Perhaps it is related to the way it is being invoked on your server? If you provide some more context such that this problem is able to be recreated, I might be able to find a solution within the library.

**Comment by jaredwinick** [comment]
As I don't have any more detail, I am going to close this issue. Thanks.
